language: node_js
node_js:
  - '12'
install: yarn
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: test
      name: "Unit Test"
      script: npm test
    - stage: release
      script: npm run semantic-release