language: node_js
node_js:
  - '8'
install: npm install
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: test
      name: "Unit Test"
      script: npm test
    - stage: release
      script: npm run semantic-release